Traceback (most recent call last):
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import yaml

import feisty

defaults = feisty.settings.get_defaults()
print(yaml.dump(defaults, default_flow_style=False, sort_keys=False))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn [1], line 3[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01myaml[39;00m
[0;32m----> 3[0m [38;5;28;01mimport[39;00m [38;5;21;01mfeisty[39;00m
[1;32m      5[0m defaults [38;5;241m=[39m feisty[38;5;241m.[39msettings[38;5;241m.[39mget_defaults()
[1;32m      6[0m [38;5;28mprint[39m(yaml[38;5;241m.[39mdump(defaults, default_flow_style[38;5;241m=[39m[38;5;28;01mFalse[39;00m, sort_keys[38;5;241m=[39m[38;5;28;01mFalse[39;00m))

[0;31mModuleNotFoundError[0m: No module named 'feisty'
ModuleNotFoundError: No module named 'feisty'

